services:
  redis-db:
    image: redis:alpine
    container_name: redis-db
    command: >
      redis-server
      --maxmemory 200mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - sd-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    networks:
      - sd-network
    depends_on:
      - redis-db

  generador_de_respuestas:
    build: ./generador_de_respuestas
    container_name: generador_de_respuestas
    volumes:
      - ./967_buildings.csv:/app/967_buildings.csv  # mounts CSV correctly
    ports:
      - "8001:8001"
    networks:
      - sd-network

  cache:
    build: ./cache
    container_name: cache
    depends_on:
      - redis-db
      - generador_de_respuestas
    ports:
      - "8000:8000"
    networks:
      - sd-network

  generador_de_trafico:
    build: ./generador_de_trafico
    container_name: generador_de_trafico
    depends_on:
      - cache
    environment:
      - RESPUESTAS_URL=http://cache:8000
    stdin_open: true
    tty: true
    networks:
      - sd-network

networks:
  sd-network:
    driver: bridge